# Generated by Django 5.2.3 on 2025-06-10 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0002_alter_task_created_at_alter_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
