# Generated by Django 5.2.3 on 2025-06-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todorestapi', '0003_remove_task_due_at_remove_task_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
